linters-settings:
  gocyclo:
    min-complexity: 20
  lll:
    line-length: 140
  maligned:
    suggest-new: true
linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    #- dupl
    - errcheck
    - exportloopref
    #- funlen
    #- gochecknoglobals
    #- gochecknoinits
    #- gocritic
    - gocyclo
    - gofmt
    - goimports
    #- golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    #- stylecheck
    #- testpackage
    - typecheck
    - unconvert
    #- unparam
    - unused
    - varcheck
    - whitespace
