//
//SPDX-License-Identifier: Apache-2.0
//
//Copyright Contributors to the Submariner project.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: pkg/natdiscovery/proto/natdiscovery.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseType int32

const (
	ResponseType_OK                   ResponseType = 0
	ResponseType_NAT_DETECTED         ResponseType = 1
	ResponseType_UNKNOWN_DST_CLUSTER  ResponseType = 2
	ResponseType_UNKNOWN_DST_ENDPOINT ResponseType = 3
	ResponseType_MALFORMED            ResponseType = 4
)

// Enum value maps for ResponseType.
var (
	ResponseType_name = map[int32]string{
		0: "OK",
		1: "NAT_DETECTED",
		2: "UNKNOWN_DST_CLUSTER",
		3: "UNKNOWN_DST_ENDPOINT",
		4: "MALFORMED",
	}
	ResponseType_value = map[string]int32{
		"OK":                   0,
		"NAT_DETECTED":         1,
		"UNKNOWN_DST_CLUSTER":  2,
		"UNKNOWN_DST_ENDPOINT": 3,
		"MALFORMED":            4,
	}
)

func (x ResponseType) Enum() *ResponseType {
	p := new(ResponseType)
	*p = x
	return p
}

func (x ResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_natdiscovery_proto_natdiscovery_proto_enumTypes[0].Descriptor()
}

func (ResponseType) Type() protoreflect.EnumType {
	return &file_pkg_natdiscovery_proto_natdiscovery_proto_enumTypes[0]
}

func (x ResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseType.Descriptor instead.
func (ResponseType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_natdiscovery_proto_natdiscovery_proto_rawDescGZIP(), []int{0}
}

type SubmarinerNATDiscoveryMessage struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*SubmarinerNATDiscoveryMessage_Request
	//	*SubmarinerNATDiscoveryMessage_Response
	Message       isSubmarinerNATDiscoveryMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmarinerNATDiscoveryMessage) Reset() {
	*x = SubmarinerNATDiscoveryMessage{}
	mi := &file_pkg_natdiscovery_proto_natdiscovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmarinerNATDiscoveryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmarinerNATDiscoveryMessage) ProtoMessage() {}

func (x *SubmarinerNATDiscoveryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_natdiscovery_proto_natdiscovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmarinerNATDiscoveryMessage.ProtoReflect.Descriptor instead.
func (*SubmarinerNATDiscoveryMessage) Descriptor() ([]byte, []int) {
	return file_pkg_natdiscovery_proto_natdiscovery_proto_rawDescGZIP(), []int{0}
}

func (x *SubmarinerNATDiscoveryMessage) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SubmarinerNATDiscoveryMessage) GetMessage() isSubmarinerNATDiscoveryMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SubmarinerNATDiscoveryMessage) GetRequest() *SubmarinerNATDiscoveryRequest {
	if x != nil {
		if x, ok := x.Message.(*SubmarinerNATDiscoveryMessage_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *SubmarinerNATDiscoveryMessage) GetResponse() *SubmarinerNATDiscoveryResponse {
	if x != nil {
		if x, ok := x.Message.(*SubmarinerNATDiscoveryMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isSubmarinerNATDiscoveryMessage_Message interface {
	isSubmarinerNATDiscoveryMessage_Message()
}

type SubmarinerNATDiscoveryMessage_Request struct {
	Request *SubmarinerNATDiscoveryRequest `protobuf:"bytes,2,opt,name=request,proto3,oneof"`
}

type SubmarinerNATDiscoveryMessage_Response struct {
	Response *SubmarinerNATDiscoveryResponse `protobuf:"bytes,3,opt,name=response,proto3,oneof"`
}

func (*SubmarinerNATDiscoveryMessage_Request) isSubmarinerNATDiscoveryMessage_Message() {}

func (*SubmarinerNATDiscoveryMessage_Response) isSubmarinerNATDiscoveryMessage_Message() {}

type SubmarinerNATDiscoveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestNumber uint64                 `protobuf:"varint,1,opt,name=request_number,json=requestNumber,proto3" json:"request_number,omitempty"`
	Sender        *EndpointDetails       `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver      *EndpointDetails       `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	// The following information would allow the receiver to identify
	// and log if any form of NAT traversal is happening on the path
	UsingSrc      *IPPortPair `protobuf:"bytes,4,opt,name=using_src,json=usingSrc,proto3" json:"using_src,omitempty"`
	UsingDst      *IPPortPair `protobuf:"bytes,5,opt,name=using_dst,json=usingDst,proto3" json:"using_dst,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmarinerNATDiscoveryRequest) Reset() {
	*x = SubmarinerNATDiscoveryRequest{}
	mi := &file_pkg_natdiscovery_proto_natdiscovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmarinerNATDiscoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmarinerNATDiscoveryRequest) ProtoMessage() {}

func (x *SubmarinerNATDiscoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_natdiscovery_proto_natdiscovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmarinerNATDiscoveryRequest.ProtoReflect.Descriptor instead.
func (*SubmarinerNATDiscoveryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_natdiscovery_proto_natdiscovery_proto_rawDescGZIP(), []int{1}
}

func (x *SubmarinerNATDiscoveryRequest) GetRequestNumber() uint64 {
	if x != nil {
		return x.RequestNumber
	}
	return 0
}

func (x *SubmarinerNATDiscoveryRequest) GetSender() *EndpointDetails {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *SubmarinerNATDiscoveryRequest) GetReceiver() *EndpointDetails {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *SubmarinerNATDiscoveryRequest) GetUsingSrc() *IPPortPair {
	if x != nil {
		return x.UsingSrc
	}
	return nil
}

func (x *SubmarinerNATDiscoveryRequest) GetUsingDst() *IPPortPair {
	if x != nil {
		return x.UsingDst
	}
	return nil
}

type SubmarinerNATDiscoveryResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RequestNumber      uint64                 `protobuf:"varint,1,opt,name=request_number,json=requestNumber,proto3" json:"request_number,omitempty"`
	Response           ResponseType           `protobuf:"varint,2,opt,name=response,proto3,enum=ResponseType" json:"response,omitempty"`
	Sender             *EndpointDetails       `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver           *EndpointDetails       `protobuf:"bytes,4,opt,name=receiver,proto3" json:"receiver,omitempty"`
	SrcIpNatDetected   bool                   `protobuf:"varint,5,opt,name=src_ip_nat_detected,json=srcIpNatDetected,proto3" json:"src_ip_nat_detected,omitempty"`
	SrcPortNatDetected bool                   `protobuf:"varint,6,opt,name=src_port_nat_detected,json=srcPortNatDetected,proto3" json:"src_port_nat_detected,omitempty"`
	DstIpNatDetected   bool                   `protobuf:"varint,7,opt,name=dst_ip_nat_detected,json=dstIpNatDetected,proto3" json:"dst_ip_nat_detected,omitempty"`
	// The received SRC IP / SRC port is reported, which will be useful for
	// diagnosing corner cases
	ReceivedSrc   *IPPortPair `protobuf:"bytes,8,opt,name=received_src,json=receivedSrc,proto3" json:"received_src,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmarinerNATDiscoveryResponse) Reset() {
	*x = SubmarinerNATDiscoveryResponse{}
	mi := &file_pkg_natdiscovery_proto_natdiscovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmarinerNATDiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmarinerNATDiscoveryResponse) ProtoMessage() {}

func (x *SubmarinerNATDiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_natdiscovery_proto_natdiscovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmarinerNATDiscoveryResponse.ProtoReflect.Descriptor instead.
func (*SubmarinerNATDiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_natdiscovery_proto_natdiscovery_proto_rawDescGZIP(), []int{2}
}

func (x *SubmarinerNATDiscoveryResponse) GetRequestNumber() uint64 {
	if x != nil {
		return x.RequestNumber
	}
	return 0
}

func (x *SubmarinerNATDiscoveryResponse) GetResponse() ResponseType {
	if x != nil {
		return x.Response
	}
	return ResponseType_OK
}

func (x *SubmarinerNATDiscoveryResponse) GetSender() *EndpointDetails {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *SubmarinerNATDiscoveryResponse) GetReceiver() *EndpointDetails {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *SubmarinerNATDiscoveryResponse) GetSrcIpNatDetected() bool {
	if x != nil {
		return x.SrcIpNatDetected
	}
	return false
}

func (x *SubmarinerNATDiscoveryResponse) GetSrcPortNatDetected() bool {
	if x != nil {
		return x.SrcPortNatDetected
	}
	return false
}

func (x *SubmarinerNATDiscoveryResponse) GetDstIpNatDetected() bool {
	if x != nil {
		return x.DstIpNatDetected
	}
	return false
}

func (x *SubmarinerNATDiscoveryResponse) GetReceivedSrc() *IPPortPair {
	if x != nil {
		return x.ReceivedSrc
	}
	return nil
}

type IPPortPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IP            string                 `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPPortPair) Reset() {
	*x = IPPortPair{}
	mi := &file_pkg_natdiscovery_proto_natdiscovery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPPortPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPPortPair) ProtoMessage() {}

func (x *IPPortPair) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_natdiscovery_proto_natdiscovery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPPortPair.ProtoReflect.Descriptor instead.
func (*IPPortPair) Descriptor() ([]byte, []int) {
	return file_pkg_natdiscovery_proto_natdiscovery_proto_rawDescGZIP(), []int{3}
}

func (x *IPPortPair) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *IPPortPair) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type EndpointDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// should we hash this for privacy? a hash can be checked against a known list, but can't be decoded
	ClusterId     string `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	EndpointId    string `protobuf:"bytes,2,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointDetails) Reset() {
	*x = EndpointDetails{}
	mi := &file_pkg_natdiscovery_proto_natdiscovery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointDetails) ProtoMessage() {}

func (x *EndpointDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_natdiscovery_proto_natdiscovery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointDetails.ProtoReflect.Descriptor instead.
func (*EndpointDetails) Descriptor() ([]byte, []int) {
	return file_pkg_natdiscovery_proto_natdiscovery_proto_rawDescGZIP(), []int{4}
}

func (x *EndpointDetails) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *EndpointDetails) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

var File_pkg_natdiscovery_proto_natdiscovery_proto protoreflect.FileDescriptor

const file_pkg_natdiscovery_proto_natdiscovery_proto_rawDesc = "" +
	"\n" +
	")pkg/natdiscovery/proto/natdiscovery.proto\"\xbf\x01\n" +
	"\x1dSubmarinerNATDiscoveryMessage\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12:\n" +
	"\arequest\x18\x02 \x01(\v2\x1e.SubmarinerNATDiscoveryRequestH\x00R\arequest\x12=\n" +
	"\bresponse\x18\x03 \x01(\v2\x1f.SubmarinerNATDiscoveryResponseH\x00R\bresponseB\t\n" +
	"\amessage\"\xf2\x01\n" +
	"\x1dSubmarinerNATDiscoveryRequest\x12%\n" +
	"\x0erequest_number\x18\x01 \x01(\x04R\rrequestNumber\x12(\n" +
	"\x06sender\x18\x02 \x01(\v2\x10.EndpointDetailsR\x06sender\x12,\n" +
	"\breceiver\x18\x03 \x01(\v2\x10.EndpointDetailsR\breceiver\x12(\n" +
	"\tusing_src\x18\x04 \x01(\v2\v.IPPortPairR\busingSrc\x12(\n" +
	"\tusing_dst\x18\x05 \x01(\v2\v.IPPortPairR\busingDst\"\x8b\x03\n" +
	"\x1eSubmarinerNATDiscoveryResponse\x12%\n" +
	"\x0erequest_number\x18\x01 \x01(\x04R\rrequestNumber\x12)\n" +
	"\bresponse\x18\x02 \x01(\x0e2\r.ResponseTypeR\bresponse\x12(\n" +
	"\x06sender\x18\x03 \x01(\v2\x10.EndpointDetailsR\x06sender\x12,\n" +
	"\breceiver\x18\x04 \x01(\v2\x10.EndpointDetailsR\breceiver\x12-\n" +
	"\x13src_ip_nat_detected\x18\x05 \x01(\bR\x10srcIpNatDetected\x121\n" +
	"\x15src_port_nat_detected\x18\x06 \x01(\bR\x12srcPortNatDetected\x12-\n" +
	"\x13dst_ip_nat_detected\x18\a \x01(\bR\x10dstIpNatDetected\x12.\n" +
	"\freceived_src\x18\b \x01(\v2\v.IPPortPairR\vreceivedSrc\"0\n" +
	"\n" +
	"IPPortPair\x12\x0e\n" +
	"\x02IP\x18\x01 \x01(\tR\x02IP\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"Q\n" +
	"\x0fEndpointDetails\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x1f\n" +
	"\vendpoint_id\x18\x02 \x01(\tR\n" +
	"endpointId*j\n" +
	"\fResponseType\x12\x06\n" +
	"\x02OK\x10\x00\x12\x10\n" +
	"\fNAT_DETECTED\x10\x01\x12\x17\n" +
	"\x13UNKNOWN_DST_CLUSTER\x10\x02\x12\x18\n" +
	"\x14UNKNOWN_DST_ENDPOINT\x10\x03\x12\r\n" +
	"\tMALFORMED\x10\x04B<Z:github.com/submariner-io/submariner/pkg/natdiscovery/protob\x06proto3"

var (
	file_pkg_natdiscovery_proto_natdiscovery_proto_rawDescOnce sync.Once
	file_pkg_natdiscovery_proto_natdiscovery_proto_rawDescData []byte
)

func file_pkg_natdiscovery_proto_natdiscovery_proto_rawDescGZIP() []byte {
	file_pkg_natdiscovery_proto_natdiscovery_proto_rawDescOnce.Do(func() {
		file_pkg_natdiscovery_proto_natdiscovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_natdiscovery_proto_natdiscovery_proto_rawDesc), len(file_pkg_natdiscovery_proto_natdiscovery_proto_rawDesc)))
	})
	return file_pkg_natdiscovery_proto_natdiscovery_proto_rawDescData
}

var file_pkg_natdiscovery_proto_natdiscovery_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_natdiscovery_proto_natdiscovery_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_natdiscovery_proto_natdiscovery_proto_goTypes = []any{
	(ResponseType)(0),                      // 0: ResponseType
	(*SubmarinerNATDiscoveryMessage)(nil),  // 1: SubmarinerNATDiscoveryMessage
	(*SubmarinerNATDiscoveryRequest)(nil),  // 2: SubmarinerNATDiscoveryRequest
	(*SubmarinerNATDiscoveryResponse)(nil), // 3: SubmarinerNATDiscoveryResponse
	(*IPPortPair)(nil),                     // 4: IPPortPair
	(*EndpointDetails)(nil),                // 5: EndpointDetails
}
var file_pkg_natdiscovery_proto_natdiscovery_proto_depIdxs = []int32{
	2,  // 0: SubmarinerNATDiscoveryMessage.request:type_name -> SubmarinerNATDiscoveryRequest
	3,  // 1: SubmarinerNATDiscoveryMessage.response:type_name -> SubmarinerNATDiscoveryResponse
	5,  // 2: SubmarinerNATDiscoveryRequest.sender:type_name -> EndpointDetails
	5,  // 3: SubmarinerNATDiscoveryRequest.receiver:type_name -> EndpointDetails
	4,  // 4: SubmarinerNATDiscoveryRequest.using_src:type_name -> IPPortPair
	4,  // 5: SubmarinerNATDiscoveryRequest.using_dst:type_name -> IPPortPair
	0,  // 6: SubmarinerNATDiscoveryResponse.response:type_name -> ResponseType
	5,  // 7: SubmarinerNATDiscoveryResponse.sender:type_name -> EndpointDetails
	5,  // 8: SubmarinerNATDiscoveryResponse.receiver:type_name -> EndpointDetails
	4,  // 9: SubmarinerNATDiscoveryResponse.received_src:type_name -> IPPortPair
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pkg_natdiscovery_proto_natdiscovery_proto_init() }
func file_pkg_natdiscovery_proto_natdiscovery_proto_init() {
	if File_pkg_natdiscovery_proto_natdiscovery_proto != nil {
		return
	}
	file_pkg_natdiscovery_proto_natdiscovery_proto_msgTypes[0].OneofWrappers = []any{
		(*SubmarinerNATDiscoveryMessage_Request)(nil),
		(*SubmarinerNATDiscoveryMessage_Response)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_natdiscovery_proto_natdiscovery_proto_rawDesc), len(file_pkg_natdiscovery_proto_natdiscovery_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_natdiscovery_proto_natdiscovery_proto_goTypes,
		DependencyIndexes: file_pkg_natdiscovery_proto_natdiscovery_proto_depIdxs,
		EnumInfos:         file_pkg_natdiscovery_proto_natdiscovery_proto_enumTypes,
		MessageInfos:      file_pkg_natdiscovery_proto_natdiscovery_proto_msgTypes,
	}.Build()
	File_pkg_natdiscovery_proto_natdiscovery_proto = out.File
	file_pkg_natdiscovery_proto_natdiscovery_proto_goTypes = nil
	file_pkg_natdiscovery_proto_natdiscovery_proto_depIdxs = nil
}
