/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// GlobalIngressIPStatusApplyConfiguration represents an declarative configuration of the GlobalIngressIPStatus type for use
// with apply.
type GlobalIngressIPStatusApplyConfiguration struct {
	Conditions  []v1.Condition `json:"conditions,omitempty"`
	AllocatedIP *string        `json:"allocatedIP,omitempty"`
}

// GlobalIngressIPStatusApplyConfiguration constructs an declarative configuration of the GlobalIngressIPStatus type for use with
// apply.
func GlobalIngressIPStatus() *GlobalIngressIPStatusApplyConfiguration {
	return &GlobalIngressIPStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *GlobalIngressIPStatusApplyConfiguration) WithConditions(values ...v1.Condition) *GlobalIngressIPStatusApplyConfiguration {
	for i := range values {
		b.Conditions = append(b.Conditions, values[i])
	}
	return b
}

// WithAllocatedIP sets the AllocatedIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllocatedIP field is set to the value of the last call.
func (b *GlobalIngressIPStatusApplyConfiguration) WithAllocatedIP(value string) *GlobalIngressIPStatusApplyConfiguration {
	b.AllocatedIP = &value
	return b
}
