/*
SPDX-License-Identifier: Apache-2.0

Copyright Contributors to the Submariner project.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// GlobalEgressIPStatusApplyConfiguration represents a declarative configuration of the GlobalEgressIPStatus type for use
// with apply.
type GlobalEgressIPStatusApplyConfiguration struct {
	Conditions   []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	AllocatedIPs []string                         `json:"allocatedIPs,omitempty"`
}

// GlobalEgressIPStatusApplyConfiguration constructs a declarative configuration of the GlobalEgressIPStatus type for use with
// apply.
func GlobalEgressIPStatus() *GlobalEgressIPStatusApplyConfiguration {
	return &GlobalEgressIPStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *GlobalEgressIPStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *GlobalEgressIPStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithAllocatedIPs adds the given value to the AllocatedIPs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllocatedIPs field.
func (b *GlobalEgressIPStatusApplyConfiguration) WithAllocatedIPs(values ...string) *GlobalEgressIPStatusApplyConfiguration {
	for i := range values {
		b.AllocatedIPs = append(b.AllocatedIPs, values[i])
	}
	return b
}
