/*
SPDX-License-Identifier: Apache-2.0

Copyright Contributors to the Submariner project.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/submariner-io/submariner/pkg/apis/submariner.io/v1"
)

// RemoteEndpointApplyConfiguration represents an declarative configuration of the RemoteEndpoint type for use
// with apply.
type RemoteEndpointApplyConfiguration struct {
	Status        *v1.ConnectionStatus              `json:"status,omitempty"`
	StatusMessage *string                           `json:"statusMessage,omitempty"`
	Spec          *EndpointSpecApplyConfiguration   `json:"spec,omitempty"`
	LatencyRTT    *LatencyRTTSpecApplyConfiguration `json:"latencyRTT,omitempty"`
}

// RemoteEndpointApplyConfiguration constructs an declarative configuration of the RemoteEndpoint type for use with
// apply.
func RemoteEndpoint() *RemoteEndpointApplyConfiguration {
	return &RemoteEndpointApplyConfiguration{}
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *RemoteEndpointApplyConfiguration) WithStatus(value v1.ConnectionStatus) *RemoteEndpointApplyConfiguration {
	b.Status = &value
	return b
}

// WithStatusMessage sets the StatusMessage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StatusMessage field is set to the value of the last call.
func (b *RemoteEndpointApplyConfiguration) WithStatusMessage(value string) *RemoteEndpointApplyConfiguration {
	b.StatusMessage = &value
	return b
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *RemoteEndpointApplyConfiguration) WithSpec(value *EndpointSpecApplyConfiguration) *RemoteEndpointApplyConfiguration {
	b.Spec = value
	return b
}

// WithLatencyRTT sets the LatencyRTT field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LatencyRTT field is set to the value of the last call.
func (b *RemoteEndpointApplyConfiguration) WithLatencyRTT(value *LatencyRTTSpecApplyConfiguration) *RemoteEndpointApplyConfiguration {
	b.LatencyRTT = value
	return b
}
