/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	submarineriov1alpha1 "github.com/submariner-io/submariner/pkg/apis/submariner.io/v1alpha1"
	versioned "github.com/submariner-io/submariner/pkg/client/clientset/versioned"
	internalinterfaces "github.com/submariner-io/submariner/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/submariner-io/submariner/pkg/client/listers/submariner.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GlobalnetEgressIPInformer provides access to a shared informer and lister for
// GlobalnetEgressIPs.
type GlobalnetEgressIPInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.GlobalnetEgressIPLister
}

type globalnetEgressIPInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGlobalnetEgressIPInformer constructs a new informer for GlobalnetEgressIP type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGlobalnetEgressIPInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGlobalnetEgressIPInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredGlobalnetEgressIPInformer constructs a new informer for GlobalnetEgressIP type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGlobalnetEgressIPInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SubmarinerV1alpha1().GlobalnetEgressIPs(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SubmarinerV1alpha1().GlobalnetEgressIPs(namespace).Watch(options)
			},
		},
		&submarineriov1alpha1.GlobalnetEgressIP{},
		resyncPeriod,
		indexers,
	)
}

func (f *globalnetEgressIPInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGlobalnetEgressIPInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *globalnetEgressIPInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&submarineriov1alpha1.GlobalnetEgressIP{}, f.defaultInformer)
}

func (f *globalnetEgressIPInformer) Lister() v1alpha1.GlobalnetEgressIPLister {
	return v1alpha1.NewGlobalnetEgressIPLister(f.Informer().GetIndexer())
}
