/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/submariner-io/submariner/pkg/apis/submariner.io/v1alpha1"
	scheme "github.com/submariner-io/submariner/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GlobalnetEgressIPsGetter has a method to return a GlobalnetEgressIPInterface.
// A group's client should implement this interface.
type GlobalnetEgressIPsGetter interface {
	GlobalnetEgressIPs(namespace string) GlobalnetEgressIPInterface
}

// GlobalnetEgressIPInterface has methods to work with GlobalnetEgressIP resources.
type GlobalnetEgressIPInterface interface {
	Create(*v1alpha1.GlobalnetEgressIP) (*v1alpha1.GlobalnetEgressIP, error)
	Update(*v1alpha1.GlobalnetEgressIP) (*v1alpha1.GlobalnetEgressIP, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.GlobalnetEgressIP, error)
	List(opts v1.ListOptions) (*v1alpha1.GlobalnetEgressIPList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GlobalnetEgressIP, err error)
	GlobalnetEgressIPExpansion
}

// globalnetEgressIPs implements GlobalnetEgressIPInterface
type globalnetEgressIPs struct {
	client rest.Interface
	ns     string
}

// newGlobalnetEgressIPs returns a GlobalnetEgressIPs
func newGlobalnetEgressIPs(c *SubmarinerV1alpha1Client, namespace string) *globalnetEgressIPs {
	return &globalnetEgressIPs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the globalnetEgressIP, and returns the corresponding globalnetEgressIP object, and an error if there is any.
func (c *globalnetEgressIPs) Get(name string, options v1.GetOptions) (result *v1alpha1.GlobalnetEgressIP, err error) {
	result = &v1alpha1.GlobalnetEgressIP{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("globalnetegressips").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GlobalnetEgressIPs that match those selectors.
func (c *globalnetEgressIPs) List(opts v1.ListOptions) (result *v1alpha1.GlobalnetEgressIPList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.GlobalnetEgressIPList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("globalnetegressips").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested globalnetEgressIPs.
func (c *globalnetEgressIPs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("globalnetegressips").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a globalnetEgressIP and creates it.  Returns the server's representation of the globalnetEgressIP, and an error, if there is any.
func (c *globalnetEgressIPs) Create(globalnetEgressIP *v1alpha1.GlobalnetEgressIP) (result *v1alpha1.GlobalnetEgressIP, err error) {
	result = &v1alpha1.GlobalnetEgressIP{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("globalnetegressips").
		Body(globalnetEgressIP).
		Do().
		Into(result)
	return
}

// Update takes the representation of a globalnetEgressIP and updates it. Returns the server's representation of the globalnetEgressIP, and an error, if there is any.
func (c *globalnetEgressIPs) Update(globalnetEgressIP *v1alpha1.GlobalnetEgressIP) (result *v1alpha1.GlobalnetEgressIP, err error) {
	result = &v1alpha1.GlobalnetEgressIP{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("globalnetegressips").
		Name(globalnetEgressIP.Name).
		Body(globalnetEgressIP).
		Do().
		Into(result)
	return
}

// Delete takes name of the globalnetEgressIP and deletes it. Returns an error if one occurs.
func (c *globalnetEgressIPs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("globalnetegressips").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *globalnetEgressIPs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("globalnetegressips").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched globalnetEgressIP.
func (c *globalnetEgressIPs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GlobalnetEgressIP, err error) {
	result = &v1alpha1.GlobalnetEgressIP{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("globalnetegressips").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
