/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	submarineriov1 "github.com/submariner-io/submariner/pkg/apis/submariner.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGatewayRoutes implements GatewayRouteInterface
type FakeGatewayRoutes struct {
	Fake *FakeSubmarinerV1
	ns   string
}

var gatewayroutesResource = schema.GroupVersionResource{Group: "submariner.io", Version: "v1", Resource: "gatewayroutes"}

var gatewayroutesKind = schema.GroupVersionKind{Group: "submariner.io", Version: "v1", Kind: "GatewayRoute"}

// Get takes name of the gatewayRoute, and returns the corresponding gatewayRoute object, and an error if there is any.
func (c *FakeGatewayRoutes) Get(ctx context.Context, name string, options v1.GetOptions) (result *submarineriov1.GatewayRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(gatewayroutesResource, c.ns, name), &submarineriov1.GatewayRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*submarineriov1.GatewayRoute), err
}

// List takes label and field selectors, and returns the list of GatewayRoutes that match those selectors.
func (c *FakeGatewayRoutes) List(ctx context.Context, opts v1.ListOptions) (result *submarineriov1.GatewayRouteList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(gatewayroutesResource, gatewayroutesKind, c.ns, opts), &submarineriov1.GatewayRouteList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &submarineriov1.GatewayRouteList{ListMeta: obj.(*submarineriov1.GatewayRouteList).ListMeta}
	for _, item := range obj.(*submarineriov1.GatewayRouteList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested gatewayRoutes.
func (c *FakeGatewayRoutes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(gatewayroutesResource, c.ns, opts))

}

// Create takes the representation of a gatewayRoute and creates it.  Returns the server's representation of the gatewayRoute, and an error, if there is any.
func (c *FakeGatewayRoutes) Create(ctx context.Context, gatewayRoute *submarineriov1.GatewayRoute, opts v1.CreateOptions) (result *submarineriov1.GatewayRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(gatewayroutesResource, c.ns, gatewayRoute), &submarineriov1.GatewayRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*submarineriov1.GatewayRoute), err
}

// Update takes the representation of a gatewayRoute and updates it. Returns the server's representation of the gatewayRoute, and an error, if there is any.
func (c *FakeGatewayRoutes) Update(ctx context.Context, gatewayRoute *submarineriov1.GatewayRoute, opts v1.UpdateOptions) (result *submarineriov1.GatewayRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(gatewayroutesResource, c.ns, gatewayRoute), &submarineriov1.GatewayRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*submarineriov1.GatewayRoute), err
}

// Delete takes name of the gatewayRoute and deletes it. Returns an error if one occurs.
func (c *FakeGatewayRoutes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(gatewayroutesResource, c.ns, name, opts), &submarineriov1.GatewayRoute{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGatewayRoutes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(gatewayroutesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &submarineriov1.GatewayRouteList{})
	return err
}

// Patch applies the patch and returns the patched gatewayRoute.
func (c *FakeGatewayRoutes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *submarineriov1.GatewayRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(gatewayroutesResource, c.ns, name, pt, data, subresources...), &submarineriov1.GatewayRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*submarineriov1.GatewayRoute), err
}
