/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	submarineriov1 "github.com/submariner-io/submariner/pkg/apis/submariner.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNonGatewayRoutes implements NonGatewayRouteInterface
type FakeNonGatewayRoutes struct {
	Fake *FakeSubmarinerV1
	ns   string
}

var nongatewayroutesResource = schema.GroupVersionResource{Group: "submariner.io", Version: "v1", Resource: "nongatewayroutes"}

var nongatewayroutesKind = schema.GroupVersionKind{Group: "submariner.io", Version: "v1", Kind: "NonGatewayRoute"}

// Get takes name of the nonGatewayRoute, and returns the corresponding nonGatewayRoute object, and an error if there is any.
func (c *FakeNonGatewayRoutes) Get(ctx context.Context, name string, options v1.GetOptions) (result *submarineriov1.NonGatewayRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(nongatewayroutesResource, c.ns, name), &submarineriov1.NonGatewayRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*submarineriov1.NonGatewayRoute), err
}

// List takes label and field selectors, and returns the list of NonGatewayRoutes that match those selectors.
func (c *FakeNonGatewayRoutes) List(ctx context.Context, opts v1.ListOptions) (result *submarineriov1.NonGatewayRouteList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(nongatewayroutesResource, nongatewayroutesKind, c.ns, opts), &submarineriov1.NonGatewayRouteList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &submarineriov1.NonGatewayRouteList{ListMeta: obj.(*submarineriov1.NonGatewayRouteList).ListMeta}
	for _, item := range obj.(*submarineriov1.NonGatewayRouteList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nonGatewayRoutes.
func (c *FakeNonGatewayRoutes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(nongatewayroutesResource, c.ns, opts))

}

// Create takes the representation of a nonGatewayRoute and creates it.  Returns the server's representation of the nonGatewayRoute, and an error, if there is any.
func (c *FakeNonGatewayRoutes) Create(ctx context.Context, nonGatewayRoute *submarineriov1.NonGatewayRoute, opts v1.CreateOptions) (result *submarineriov1.NonGatewayRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(nongatewayroutesResource, c.ns, nonGatewayRoute), &submarineriov1.NonGatewayRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*submarineriov1.NonGatewayRoute), err
}

// Update takes the representation of a nonGatewayRoute and updates it. Returns the server's representation of the nonGatewayRoute, and an error, if there is any.
func (c *FakeNonGatewayRoutes) Update(ctx context.Context, nonGatewayRoute *submarineriov1.NonGatewayRoute, opts v1.UpdateOptions) (result *submarineriov1.NonGatewayRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(nongatewayroutesResource, c.ns, nonGatewayRoute), &submarineriov1.NonGatewayRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*submarineriov1.NonGatewayRoute), err
}

// Delete takes name of the nonGatewayRoute and deletes it. Returns an error if one occurs.
func (c *FakeNonGatewayRoutes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(nongatewayroutesResource, c.ns, name, opts), &submarineriov1.NonGatewayRoute{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNonGatewayRoutes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(nongatewayroutesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &submarineriov1.NonGatewayRouteList{})
	return err
}

// Patch applies the patch and returns the patched nonGatewayRoute.
func (c *FakeNonGatewayRoutes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *submarineriov1.NonGatewayRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nongatewayroutesResource, c.ns, name, pt, data, subresources...), &submarineriov1.NonGatewayRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*submarineriov1.NonGatewayRoute), err
}
