/*
SPDX-License-Identifier: Apache-2.0

Copyright Contributors to the Submariner project.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apissubmarineriov1 "github.com/submariner-io/submariner/pkg/apis/submariner.io/v1"
	versioned "github.com/submariner-io/submariner/pkg/client/clientset/versioned"
	internalinterfaces "github.com/submariner-io/submariner/pkg/client/informers/externalversions/internalinterfaces"
	submarineriov1 "github.com/submariner-io/submariner/pkg/client/listers/submariner.io/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterInformer provides access to a shared informer and lister for
// Clusters. Prefer using the type-safe variant (see [TypedClusterInformer]).
type ClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() submarineriov1.ClusterLister
}

// TypedClusterInformer provides access to a shared informer and lister for
// Clusters, including the type-safe TypedInformer variant.
// It is a superset of ClusterInformer.
type TypedClusterInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() ClusterIndexInformer
	Lister() submarineriov1.ClusterLister
}

// ClusterIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type ClusterIndexInformer cache.TypedSharedIndexInformer[*apissubmarineriov1.Cluster]

// ClusterHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for Cluster.
type ClusterHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apissubmarineriov1.Cluster]

// ClusterDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for Cluster.
type ClusterDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apissubmarineriov1.Cluster]

// ClusterFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for Cluster.
type ClusterFilteringHandler = cache.TypedFilteringResourceEventHandler[*apissubmarineriov1.Cluster]

// ClusterIndexers is a specialization of [cache.TypedIndexers] for Cluster.
type ClusterIndexers = cache.TypedIndexers[*apissubmarineriov1.Cluster]

// DeletedCluster is a specialization of [cache.DeletedObject] for Cluster.
type DeletedCluster = cache.DeletedObject[*apissubmarineriov1.Cluster]

type clusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewClusterInformer constructs a new informer for Cluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedClusterInformer]).
func NewClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewClusterInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedClusterInformer constructs a new informer for Cluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers ClusterIndexers) ClusterIndexInformer {
	return NewTypedClusterInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredClusterInformer constructs a new informer for Cluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredClusterInformer]).
func NewFilteredClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedClusterInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredClusterInformer constructs a new informer for Cluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers ClusterIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) ClusterIndexInformer {
	return NewTypedClusterInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewClusterInformerWithOptions constructs a new informer for Cluster type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedClusterInformerWithOptions]).
func NewClusterInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedClusterInformerWithOptions(client, namespace, options)
}

// NewTypedClusterInformerWithOptions constructs a new informer for Cluster type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedClusterInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) ClusterIndexInformer {
	gvr := schema.GroupVersionResource{Group: "submariner.io", Version: "v1", Resource: "clusters"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apissubmarineriov1.Cluster](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.SubmarinerV1().Clusters(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.SubmarinerV1().Clusters(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.SubmarinerV1().Clusters(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.SubmarinerV1().Clusters(namespace).Watch(ctx, opts)
			},
		}, client),
		&apissubmarineriov1.Cluster{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *clusterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedClusterInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *clusterInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *clusterInformer) TypedInformer() ClusterIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apissubmarineriov1.Cluster](f.factory.InformerFor(&apissubmarineriov1.Cluster{}, f.defaultInformer))
}

func (f *clusterInformer) Lister() submarineriov1.ClusterLister {
	return submarineriov1.NewClusterLister(f.Informer().GetIndexer())
}

// ToTypedClusterInformer converts an untyped informer into a TypedClusterInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *Cluster. If that is not the case, calling type-safe methods of the returned
// TypedClusterInformer leads to runtime panics. A safer alternative is to pass
// around a TypedClusterInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedClusterInformer(informer ClusterInformer) TypedClusterInformer {
	if informer, ok := informer.(TypedClusterInformer); ok {
		return informer
	}
	return &clusterTypedInformerAdapter{informer}
}

type clusterTypedInformerAdapter struct {
	ClusterInformer
}

func (a *clusterTypedInformerAdapter) TypedInformer() ClusterIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apissubmarineriov1.Cluster](a.Informer())
}

// ToClusterIndexInformer converts an untyped informer into a ClusterIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *Cluster. If that is not the case, calling type-safe methods of the returned
// ClusterIndexInformer leads to runtime panics. A safer alternative is to pass
// around a ClusterIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToClusterIndexInformer(informer cache.SharedIndexInformer) ClusterIndexInformer {
	if informer, ok := informer.(ClusterIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apissubmarineriov1.Cluster](informer)
}
