/*
SPDX-License-Identifier: Apache-2.0

Copyright Contributors to the Submariner project.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apissubmarineriov1 "github.com/submariner-io/submariner/pkg/apis/submariner.io/v1"
	versioned "github.com/submariner-io/submariner/pkg/client/clientset/versioned"
	internalinterfaces "github.com/submariner-io/submariner/pkg/client/informers/externalversions/internalinterfaces"
	submarineriov1 "github.com/submariner-io/submariner/pkg/client/listers/submariner.io/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GlobalIngressIPInformer provides access to a shared informer and lister for
// GlobalIngressIPs. Prefer using the type-safe variant (see [TypedGlobalIngressIPInformer]).
type GlobalIngressIPInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() submarineriov1.GlobalIngressIPLister
}

// TypedGlobalIngressIPInformer provides access to a shared informer and lister for
// GlobalIngressIPs, including the type-safe TypedInformer variant.
// It is a superset of GlobalIngressIPInformer.
type TypedGlobalIngressIPInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() GlobalIngressIPIndexInformer
	Lister() submarineriov1.GlobalIngressIPLister
}

// GlobalIngressIPIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type GlobalIngressIPIndexInformer cache.TypedSharedIndexInformer[*apissubmarineriov1.GlobalIngressIP]

// GlobalIngressIPHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for GlobalIngressIP.
type GlobalIngressIPHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apissubmarineriov1.GlobalIngressIP]

// GlobalIngressIPDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for GlobalIngressIP.
type GlobalIngressIPDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apissubmarineriov1.GlobalIngressIP]

// GlobalIngressIPFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for GlobalIngressIP.
type GlobalIngressIPFilteringHandler = cache.TypedFilteringResourceEventHandler[*apissubmarineriov1.GlobalIngressIP]

// GlobalIngressIPIndexers is a specialization of [cache.TypedIndexers] for GlobalIngressIP.
type GlobalIngressIPIndexers = cache.TypedIndexers[*apissubmarineriov1.GlobalIngressIP]

// DeletedGlobalIngressIP is a specialization of [cache.DeletedObject] for GlobalIngressIP.
type DeletedGlobalIngressIP = cache.DeletedObject[*apissubmarineriov1.GlobalIngressIP]

type globalIngressIPInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGlobalIngressIPInformer constructs a new informer for GlobalIngressIP type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedGlobalIngressIPInformer]).
func NewGlobalIngressIPInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewGlobalIngressIPInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedGlobalIngressIPInformer constructs a new informer for GlobalIngressIP type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedGlobalIngressIPInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers GlobalIngressIPIndexers) GlobalIngressIPIndexInformer {
	return NewTypedGlobalIngressIPInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredGlobalIngressIPInformer constructs a new informer for GlobalIngressIP type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredGlobalIngressIPInformer]).
func NewFilteredGlobalIngressIPInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedGlobalIngressIPInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredGlobalIngressIPInformer constructs a new informer for GlobalIngressIP type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredGlobalIngressIPInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers GlobalIngressIPIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) GlobalIngressIPIndexInformer {
	return NewTypedGlobalIngressIPInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewGlobalIngressIPInformerWithOptions constructs a new informer for GlobalIngressIP type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedGlobalIngressIPInformerWithOptions]).
func NewGlobalIngressIPInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedGlobalIngressIPInformerWithOptions(client, namespace, options)
}

// NewTypedGlobalIngressIPInformerWithOptions constructs a new informer for GlobalIngressIP type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedGlobalIngressIPInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) GlobalIngressIPIndexInformer {
	gvr := schema.GroupVersionResource{Group: "submariner.io", Version: "v1", Resource: "globalingressips"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apissubmarineriov1.GlobalIngressIP](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.SubmarinerV1().GlobalIngressIPs(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.SubmarinerV1().GlobalIngressIPs(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.SubmarinerV1().GlobalIngressIPs(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.SubmarinerV1().GlobalIngressIPs(namespace).Watch(ctx, opts)
			},
		}, client),
		&apissubmarineriov1.GlobalIngressIP{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *globalIngressIPInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedGlobalIngressIPInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *globalIngressIPInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *globalIngressIPInformer) TypedInformer() GlobalIngressIPIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apissubmarineriov1.GlobalIngressIP](f.factory.InformerFor(&apissubmarineriov1.GlobalIngressIP{}, f.defaultInformer))
}

func (f *globalIngressIPInformer) Lister() submarineriov1.GlobalIngressIPLister {
	return submarineriov1.NewGlobalIngressIPLister(f.Informer().GetIndexer())
}

// ToTypedGlobalIngressIPInformer converts an untyped informer into a TypedGlobalIngressIPInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *GlobalIngressIP. If that is not the case, calling type-safe methods of the returned
// TypedGlobalIngressIPInformer leads to runtime panics. A safer alternative is to pass
// around a TypedGlobalIngressIPInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedGlobalIngressIPInformer(informer GlobalIngressIPInformer) TypedGlobalIngressIPInformer {
	if informer, ok := informer.(TypedGlobalIngressIPInformer); ok {
		return informer
	}
	return &globalIngressIPTypedInformerAdapter{informer}
}

type globalIngressIPTypedInformerAdapter struct {
	GlobalIngressIPInformer
}

func (a *globalIngressIPTypedInformerAdapter) TypedInformer() GlobalIngressIPIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apissubmarineriov1.GlobalIngressIP](a.Informer())
}

// ToGlobalIngressIPIndexInformer converts an untyped informer into a GlobalIngressIPIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *GlobalIngressIP. If that is not the case, calling type-safe methods of the returned
// GlobalIngressIPIndexInformer leads to runtime panics. A safer alternative is to pass
// around a GlobalIngressIPIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToGlobalIngressIPIndexInformer(informer cache.SharedIndexInformer) GlobalIngressIPIndexInformer {
	if informer, ok := informer.(GlobalIngressIPIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apissubmarineriov1.GlobalIngressIP](informer)
}
