/*
SPDX-License-Identifier: Apache-2.0

Copyright Contributors to the Submariner project.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/submariner-io/submariner/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Clusters returns a ClusterInformer.
	Clusters() TypedClusterInformer
	// ClusterGlobalEgressIPs returns a ClusterGlobalEgressIPInformer.
	ClusterGlobalEgressIPs() TypedClusterGlobalEgressIPInformer
	// Endpoints returns a EndpointInformer.
	Endpoints() TypedEndpointInformer
	// Gateways returns a GatewayInformer.
	Gateways() TypedGatewayInformer
	// GatewayRoutes returns a GatewayRouteInformer.
	GatewayRoutes() TypedGatewayRouteInformer
	// GlobalEgressIPs returns a GlobalEgressIPInformer.
	GlobalEgressIPs() TypedGlobalEgressIPInformer
	// GlobalIngressIPs returns a GlobalIngressIPInformer.
	GlobalIngressIPs() TypedGlobalIngressIPInformer
	// NonGatewayRoutes returns a NonGatewayRouteInformer.
	NonGatewayRoutes() TypedNonGatewayRouteInformer
	// RouteAgents returns a RouteAgentInformer.
	RouteAgents() TypedRouteAgentInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Clusters returns a TypedClusterInformer.
func (v *version) Clusters() TypedClusterInformer {
	return &clusterInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ClusterGlobalEgressIPs returns a TypedClusterGlobalEgressIPInformer.
func (v *version) ClusterGlobalEgressIPs() TypedClusterGlobalEgressIPInformer {
	return &clusterGlobalEgressIPInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Endpoints returns a TypedEndpointInformer.
func (v *version) Endpoints() TypedEndpointInformer {
	return &endpointInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Gateways returns a TypedGatewayInformer.
func (v *version) Gateways() TypedGatewayInformer {
	return &gatewayInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// GatewayRoutes returns a TypedGatewayRouteInformer.
func (v *version) GatewayRoutes() TypedGatewayRouteInformer {
	return &gatewayRouteInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// GlobalEgressIPs returns a TypedGlobalEgressIPInformer.
func (v *version) GlobalEgressIPs() TypedGlobalEgressIPInformer {
	return &globalEgressIPInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// GlobalIngressIPs returns a TypedGlobalIngressIPInformer.
func (v *version) GlobalIngressIPs() TypedGlobalIngressIPInformer {
	return &globalIngressIPInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// NonGatewayRoutes returns a TypedNonGatewayRouteInformer.
func (v *version) NonGatewayRoutes() TypedNonGatewayRouteInformer {
	return &nonGatewayRouteInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// RouteAgents returns a TypedRouteAgentInformer.
func (v *version) RouteAgents() TypedRouteAgentInformer {
	return &routeAgentInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
