/*
SPDX-License-Identifier: Apache-2.0

Copyright Contributors to the Submariner project.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	v1 "github.com/submariner-io/submariner/pkg/apis/submariner.io/v1"
	submarineriov1 "github.com/submariner-io/submariner/pkg/client/applyconfiguration/submariner.io/v1"
	scheme "github.com/submariner-io/submariner/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// EndpointsGetter has a method to return a EndpointInterface.
// A group's client should implement this interface.
type EndpointsGetter interface {
	Endpoints(namespace string) EndpointInterface
}

// EndpointInterface has methods to work with Endpoint resources.
type EndpointInterface interface {
	Create(ctx context.Context, endpoint *v1.Endpoint, opts metav1.CreateOptions) (*v1.Endpoint, error)
	Update(ctx context.Context, endpoint *v1.Endpoint, opts metav1.UpdateOptions) (*v1.Endpoint, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Endpoint, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.EndpointList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Endpoint, err error)
	Apply(ctx context.Context, endpoint *submarineriov1.EndpointApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Endpoint, err error)
	EndpointExpansion
}

// endpoints implements EndpointInterface
type endpoints struct {
	*gentype.ClientWithListAndApply[*v1.Endpoint, *v1.EndpointList, *submarineriov1.EndpointApplyConfiguration]
}

// newEndpoints returns a Endpoints
func newEndpoints(c *SubmarinerV1Client, namespace string) *endpoints {
	return &endpoints{
		gentype.NewClientWithListAndApply[*v1.Endpoint, *v1.EndpointList, *submarineriov1.EndpointApplyConfiguration](
			"endpoints",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1.Endpoint { return &v1.Endpoint{} },
			func() *v1.EndpointList { return &v1.EndpointList{} }),
	}
}
