/*
SPDX-License-Identifier: Apache-2.0

Copyright Contributors to the Submariner project.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	v1 "github.com/submariner-io/submariner/pkg/apis/submariner.io/v1"
	submarineriov1 "github.com/submariner-io/submariner/pkg/client/applyconfiguration/submariner.io/v1"
	scheme "github.com/submariner-io/submariner/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// GatewayRoutesGetter has a method to return a GatewayRouteInterface.
// A group's client should implement this interface.
type GatewayRoutesGetter interface {
	GatewayRoutes(namespace string) GatewayRouteInterface
}

// GatewayRouteInterface has methods to work with GatewayRoute resources.
type GatewayRouteInterface interface {
	Create(ctx context.Context, gatewayRoute *v1.GatewayRoute, opts metav1.CreateOptions) (*v1.GatewayRoute, error)
	Update(ctx context.Context, gatewayRoute *v1.GatewayRoute, opts metav1.UpdateOptions) (*v1.GatewayRoute, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.GatewayRoute, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.GatewayRouteList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.GatewayRoute, err error)
	Apply(ctx context.Context, gatewayRoute *submarineriov1.GatewayRouteApplyConfiguration, opts metav1.ApplyOptions) (result *v1.GatewayRoute, err error)
	GatewayRouteExpansion
}

// gatewayRoutes implements GatewayRouteInterface
type gatewayRoutes struct {
	*gentype.ClientWithListAndApply[*v1.GatewayRoute, *v1.GatewayRouteList, *submarineriov1.GatewayRouteApplyConfiguration]
}

// newGatewayRoutes returns a GatewayRoutes
func newGatewayRoutes(c *SubmarinerV1Client, namespace string) *gatewayRoutes {
	return &gatewayRoutes{
		gentype.NewClientWithListAndApply[*v1.GatewayRoute, *v1.GatewayRouteList, *submarineriov1.GatewayRouteApplyConfiguration](
			"gatewayroutes",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1.GatewayRoute { return &v1.GatewayRoute{} },
			func() *v1.GatewayRouteList { return &v1.GatewayRouteList{} }),
	}
}
