/*
SPDX-License-Identifier: Apache-2.0

Copyright Contributors to the Submariner project.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	v1 "github.com/submariner-io/submariner/pkg/apis/submariner.io/v1"
	submarineriov1 "github.com/submariner-io/submariner/pkg/client/applyconfiguration/submariner.io/v1"
	scheme "github.com/submariner-io/submariner/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// GlobalEgressIPsGetter has a method to return a GlobalEgressIPInterface.
// A group's client should implement this interface.
type GlobalEgressIPsGetter interface {
	GlobalEgressIPs(namespace string) GlobalEgressIPInterface
}

// GlobalEgressIPInterface has methods to work with GlobalEgressIP resources.
type GlobalEgressIPInterface interface {
	Create(ctx context.Context, globalEgressIP *v1.GlobalEgressIP, opts metav1.CreateOptions) (*v1.GlobalEgressIP, error)
	Update(ctx context.Context, globalEgressIP *v1.GlobalEgressIP, opts metav1.UpdateOptions) (*v1.GlobalEgressIP, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, globalEgressIP *v1.GlobalEgressIP, opts metav1.UpdateOptions) (*v1.GlobalEgressIP, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.GlobalEgressIP, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.GlobalEgressIPList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.GlobalEgressIP, err error)
	Apply(ctx context.Context, globalEgressIP *submarineriov1.GlobalEgressIPApplyConfiguration, opts metav1.ApplyOptions) (result *v1.GlobalEgressIP, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, globalEgressIP *submarineriov1.GlobalEgressIPApplyConfiguration, opts metav1.ApplyOptions) (result *v1.GlobalEgressIP, err error)
	GlobalEgressIPExpansion
}

// globalEgressIPs implements GlobalEgressIPInterface
type globalEgressIPs struct {
	*gentype.ClientWithListAndApply[*v1.GlobalEgressIP, *v1.GlobalEgressIPList, *submarineriov1.GlobalEgressIPApplyConfiguration]
}

// newGlobalEgressIPs returns a GlobalEgressIPs
func newGlobalEgressIPs(c *SubmarinerV1Client, namespace string) *globalEgressIPs {
	return &globalEgressIPs{
		gentype.NewClientWithListAndApply[*v1.GlobalEgressIP, *v1.GlobalEgressIPList, *submarineriov1.GlobalEgressIPApplyConfiguration](
			"globalegressips",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1.GlobalEgressIP { return &v1.GlobalEgressIP{} },
			func() *v1.GlobalEgressIPList { return &v1.GlobalEgressIPList{} }),
	}
}
