/*
SPDX-License-Identifier: Apache-2.0

Copyright Contributors to the Submariner project.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	v1 "github.com/submariner-io/submariner/pkg/apis/submariner.io/v1"
	submarineriov1 "github.com/submariner-io/submariner/pkg/client/applyconfiguration/submariner.io/v1"
	scheme "github.com/submariner-io/submariner/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// GlobalIngressIPsGetter has a method to return a GlobalIngressIPInterface.
// A group's client should implement this interface.
type GlobalIngressIPsGetter interface {
	GlobalIngressIPs(namespace string) GlobalIngressIPInterface
}

// GlobalIngressIPInterface has methods to work with GlobalIngressIP resources.
type GlobalIngressIPInterface interface {
	Create(ctx context.Context, globalIngressIP *v1.GlobalIngressIP, opts metav1.CreateOptions) (*v1.GlobalIngressIP, error)
	Update(ctx context.Context, globalIngressIP *v1.GlobalIngressIP, opts metav1.UpdateOptions) (*v1.GlobalIngressIP, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, globalIngressIP *v1.GlobalIngressIP, opts metav1.UpdateOptions) (*v1.GlobalIngressIP, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.GlobalIngressIP, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.GlobalIngressIPList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.GlobalIngressIP, err error)
	Apply(ctx context.Context, globalIngressIP *submarineriov1.GlobalIngressIPApplyConfiguration, opts metav1.ApplyOptions) (result *v1.GlobalIngressIP, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, globalIngressIP *submarineriov1.GlobalIngressIPApplyConfiguration, opts metav1.ApplyOptions) (result *v1.GlobalIngressIP, err error)
	GlobalIngressIPExpansion
}

// globalIngressIPs implements GlobalIngressIPInterface
type globalIngressIPs struct {
	*gentype.ClientWithListAndApply[*v1.GlobalIngressIP, *v1.GlobalIngressIPList, *submarineriov1.GlobalIngressIPApplyConfiguration]
}

// newGlobalIngressIPs returns a GlobalIngressIPs
func newGlobalIngressIPs(c *SubmarinerV1Client, namespace string) *globalIngressIPs {
	return &globalIngressIPs{
		gentype.NewClientWithListAndApply[*v1.GlobalIngressIP, *v1.GlobalIngressIPList, *submarineriov1.GlobalIngressIPApplyConfiguration](
			"globalingressips",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1.GlobalIngressIP { return &v1.GlobalIngressIP{} },
			func() *v1.GlobalIngressIPList { return &v1.GlobalIngressIPList{} }),
	}
}
