/*
SPDX-License-Identifier: Apache-2.0

Copyright Contributors to the Submariner project.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	v1 "github.com/submariner-io/submariner/pkg/apis/submariner.io/v1"
	submarineriov1 "github.com/submariner-io/submariner/pkg/client/applyconfiguration/submariner.io/v1"
	scheme "github.com/submariner-io/submariner/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// NonGatewayRoutesGetter has a method to return a NonGatewayRouteInterface.
// A group's client should implement this interface.
type NonGatewayRoutesGetter interface {
	NonGatewayRoutes(namespace string) NonGatewayRouteInterface
}

// NonGatewayRouteInterface has methods to work with NonGatewayRoute resources.
type NonGatewayRouteInterface interface {
	Create(ctx context.Context, nonGatewayRoute *v1.NonGatewayRoute, opts metav1.CreateOptions) (*v1.NonGatewayRoute, error)
	Update(ctx context.Context, nonGatewayRoute *v1.NonGatewayRoute, opts metav1.UpdateOptions) (*v1.NonGatewayRoute, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.NonGatewayRoute, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.NonGatewayRouteList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.NonGatewayRoute, err error)
	Apply(ctx context.Context, nonGatewayRoute *submarineriov1.NonGatewayRouteApplyConfiguration, opts metav1.ApplyOptions) (result *v1.NonGatewayRoute, err error)
	NonGatewayRouteExpansion
}

// nonGatewayRoutes implements NonGatewayRouteInterface
type nonGatewayRoutes struct {
	*gentype.ClientWithListAndApply[*v1.NonGatewayRoute, *v1.NonGatewayRouteList, *submarineriov1.NonGatewayRouteApplyConfiguration]
}

// newNonGatewayRoutes returns a NonGatewayRoutes
func newNonGatewayRoutes(c *SubmarinerV1Client, namespace string) *nonGatewayRoutes {
	return &nonGatewayRoutes{
		gentype.NewClientWithListAndApply[*v1.NonGatewayRoute, *v1.NonGatewayRouteList, *submarineriov1.NonGatewayRouteApplyConfiguration](
			"nongatewayroutes",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1.NonGatewayRoute { return &v1.NonGatewayRoute{} },
			func() *v1.NonGatewayRouteList { return &v1.NonGatewayRouteList{} }),
	}
}
