/*
SPDX-License-Identifier: Apache-2.0

Copyright Contributors to the Submariner project.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	v1 "github.com/submariner-io/submariner/pkg/apis/submariner.io/v1"
	submarineriov1 "github.com/submariner-io/submariner/pkg/client/applyconfiguration/submariner.io/v1"
	scheme "github.com/submariner-io/submariner/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RouteAgentsGetter has a method to return a RouteAgentInterface.
// A group's client should implement this interface.
type RouteAgentsGetter interface {
	RouteAgents(namespace string) RouteAgentInterface
}

// RouteAgentInterface has methods to work with RouteAgent resources.
type RouteAgentInterface interface {
	Create(ctx context.Context, routeAgent *v1.RouteAgent, opts metav1.CreateOptions) (*v1.RouteAgent, error)
	Update(ctx context.Context, routeAgent *v1.RouteAgent, opts metav1.UpdateOptions) (*v1.RouteAgent, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.RouteAgent, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.RouteAgentList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.RouteAgent, err error)
	Apply(ctx context.Context, routeAgent *submarineriov1.RouteAgentApplyConfiguration, opts metav1.ApplyOptions) (result *v1.RouteAgent, err error)
	RouteAgentExpansion
}

// routeAgents implements RouteAgentInterface
type routeAgents struct {
	*gentype.ClientWithListAndApply[*v1.RouteAgent, *v1.RouteAgentList, *submarineriov1.RouteAgentApplyConfiguration]
}

// newRouteAgents returns a RouteAgents
func newRouteAgents(c *SubmarinerV1Client, namespace string) *routeAgents {
	return &routeAgents{
		gentype.NewClientWithListAndApply[*v1.RouteAgent, *v1.RouteAgentList, *submarineriov1.RouteAgentApplyConfiguration](
			"routeagents",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1.RouteAgent { return &v1.RouteAgent{} },
			func() *v1.RouteAgentList { return &v1.RouteAgentList{} }),
	}
}
