#!/bin/sh

cd $(dirname $0)

mkdir publish

cp submariner-operator/deploy/namespace.yaml publish/submariner-namespace.yaml

for f in submariner-operator/deploy/crds/*_crd.yaml
do
    echo ---
    cat $f
done > publish/submariner-crds.yaml

for f in submariner-operator/deploy/service_account.yaml \
         submariner-operator/deploy/role.yaml \
         submariner-operator/deploy/role_binding.yaml \
         submariner-operator/deploy/operator.yaml
do
    echo ---
    cat $f
done > publish/submariner-operator.yaml
