#!/bin/bash

set -e

source ${SCRIPTS_DIR}/lib/debug_functions
source ${SCRIPTS_DIR}/lib/version

cd ${DAPPER_SOURCE}

ldflags="-X main.VERSION=$VERSION"
${SCRIPTS_DIR}/compile.sh --ldflags "$ldflags" bin/submariner-engine main.go "$@"
${SCRIPTS_DIR}/compile.sh --ldflags "$ldflags" bin/submariner-route-agent ./pkg/routeagent/main.go "$@"
${SCRIPTS_DIR}/compile.sh --ldflags "$ldflags" bin/submariner-globalnet ./pkg/globalnet/main.go "$@"
