#!/bin/bash
set -e

source $(dirname $0)/lib/debug_functions

source $(dirname $0)/version

cd $(dirname $0)/..
mkdir -p bin
echo Building submariner-engine version $VERSION
CGO_ENABLED=0 go build -ldflags "-X main.VERSION=$VERSION" -o bin/submariner-engine main.go
