#!/bin/bash
set -e

source $(git rev-parse --show-toplevel)/scripts/lib/debug_functions

source $(dirname $0)/version

cd $(dirname $0)/..
mkdir -p bin
echo Building submariner-route-agent version $VERSION
CGO_ENABLED=0 go build -ldflags "-X main.VERSION=$VERSION" -o bin/submariner-route-agent ./pkg/routeagent/main.go
