#!/bin/bash
set -e

source $(dirname $0)/lib/debug_functions
source $(dirname $0)/lib/version

cd $(dirname $0)/

./build-engine
./build-routeagent

if [[ $5 = operator ]]; then
   test -d ../operators/go/submariner-operator || ./codegen-operator
   ./build-operator
fi
