#!/bin/bash

set -e
source "${SCRIPTS_DIR}"/lib/debug_functions

CODEGEN_SCRIPT_DIR=$(go -C tools mod download -json k8s.io/code-generator | jq -r .Dir)
CODEGEN_SCRIPT="${CODEGEN_SCRIPT_DIR}/kube_codegen.sh"

# shellcheck disable=SC2034 # DEBUG_PRINT is used in the debug trap
DEBUG_PRINT=
# shellcheck disable=SC1090 # No need to lint a third-party script
. "${CODEGEN_SCRIPT}"
kube::codegen::gen_helpers \
    --boilerplate scripts/boilerplate.go.txt \
    pkg/apis
kube::codegen::gen_client \
    --output-dir pkg/client \
    --output-pkg github.com/submariner-io/submariner/pkg/client \
    --boilerplate scripts/boilerplate.go.txt \
    --with-applyconfig \
    --with-watch \
    --one-input-api submariner.io \
    pkg/apis
