#!/bin/bash
set -e

source $(git rev-parse --show-toplevel)/scripts/lib/debug_functions

trap "chown -R $DAPPER_UID:$DAPPER_GID ." exit

mkdir -p bin dist output

# download all go mod modules to the vendor directory 
if [[ ! -d vendor ]]; then
	./scripts/vendor
else
	echo "Skipping go modules download as your vendor directory is already populated"
fi

if [ -e ./scripts/$1 ]; then
    ./scripts/"$@"
else
    "$@"
fi


