#!/bin/bash
set -e

source $(dirname $0)/lib/debug_functions
source $(dirname $0)/lib/version

extra_flags="$@"

cd $(dirname $0)/../package

cp ../bin/submariner-engine submariner-engine
cp ../bin/submariner-route-agent submariner-route-agent
cp ../bin/submariner-globalnet submariner-globalnet

${SCRIPTS_DIR}/build_image.sh -i submariner -f Dockerfile ${extra_flags}
${SCRIPTS_DIR}/build_image.sh -i submariner-route-agent -f Dockerfile.routeagent ${extra_flags}
${SCRIPTS_DIR}/build_image.sh -i submariner-globalnet -f Dockerfile.globalnet ${extra_flags}

