#!/bin/bash
set -e

source $(dirname $0)/lib/debug_functions
source $(dirname $0)/lib/version

ARCH=${ARCH:-"amd64"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

cd $(dirname $0)/../package

cp ../bin/submariner-engine submariner-engine
cp ../bin/submariner-route-agent submariner-route-agent

IMAGE=${REPO}/submariner:${TAG}
ROUTEAGENT_IMAGE=${REPO}/submariner-route-agent:${TAG}

docker build -t ${IMAGE} .
docker build -t ${ROUTEAGENT_IMAGE} -f Dockerfile.routeagent .

echo "Built submariner to image: ${IMAGE} and submariner-route-agent to image: ${ROUTEAGENT_IMAGE}"
