#!/usr/bin/env bash
set -e

source $(git rev-parse --show-toplevel)/scripts/lib/debug_functions

echo "$QUAY_PASSWORD" | docker login quay.io -u "$QUAY_USERNAME" --password-stdin
docker tag rancher/submariner:dev quay.io/submariner/submariner:latest
docker tag rancher/submariner:dev quay.io/submariner/submariner:"${TRAVIS_COMMIT:0:7}"
docker tag rancher/submariner-route-agent:dev quay.io/submariner/submariner-route-agent:latest
docker tag rancher/submariner-route-agent:dev quay.io/submariner/submariner-route-agent:"${TRAVIS_COMMIT:0:7}"
for i in $(docker images --format "{{.Repository}}:{{.Tag}}" | grep "quay.io/submariner"); do docker push $i; done
