#!/usr/bin/env bash

set -em

source ${SCRIPTS_DIR}/lib/debug_functions
source ${SCRIPTS_DIR}/lib/version
source ${SCRIPTS_DIR}/lib/deploy_funcs

import_image quay.io/submariner/submariner
import_image quay.io/submariner/submariner-route-agent
import_image quay.io/submariner/submariner-globalnet

