#!/bin/bash
set -e

source $(git rev-parse --show-toplevel)/scripts/lib/debug_functions

cd $(dirname $0)/..

source scripts/lib/find_functions

echo Looking for packages to test

PACKAGES=$(find_go_pkg_dirs)

echo Running tests in ${PACKAGES}
[ "${ARCH}" == "amd64" ] && RACE=-race
ginkgo ${RACE} -cover ${PACKAGES}
