#!/bin/bash
set -e

source $(dirname $0)/lib/debug_functions

cd $(git rev-parse --show-toplevel)

EXCLUDE_PKG_DIRS=".git .trash-cache vendor bin"

PACKAGES=$(find_go_pkg_dirs --no-trailing-dots "*.go")

echo Validating \"$PACKAGES\" under $(pwd)

if [[ $(goimports -l ${PACKAGES} | wc -l) -gt 0 ]]; then
    echo Incorrect formatting, please run goimports
    exit 1
fi

golangci-lint run
