#!/bin/bash
set -e

source $(dirname $0)/lib/debug_functions

source $(dirname $0)/version

cd $(dirname $0)/..
echo "Downloading go modules to cache ----"
go mod download
echo "Download finished ------------------"
echo ""
go mod vendor
