ARG BASE_BRANCH
FROM quay.io/submariner/submariner-buildenv:${BASE_BRANCH} AS build-env
ARG TARGETPLATFORM

FROM scratch
ARG TARGETPLATFORM

COPY --from=build-env /output/networkplugin-syncer /

WORKDIR /var/submariner

# install the networkpluginc-sync
COPY package/submariner-networkplugin-syncer.sh bin/${TARGETPLATFORM}/submariner-networkplugin-syncer /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/submariner-networkplugin-syncer.sh"]

USER ${USER_UID}
