ARG BASE_BRANCH
FROM quay.io/submariner/submariner-buildenv:${BASE_BRANCH} AS build-env
ARG TARGETPLATFORM

FROM scratch
ARG TARGETPLATFORM

COPY --from=build-env /output/route-agent /

WORKDIR /var/submariner

COPY package/submariner-route-agent.sh bin/${TARGETPLATFORM}/submariner-route-agent /usr/local/bin/

# Wrapper scripts to choose the appropriate iptables
# https://github.com/kubernetes-sigs/iptables-wrappers
COPY package/iptables-wrapper-installer.sh /usr/sbin/
RUN /usr/sbin/iptables-wrapper-installer.sh

ENTRYPOINT submariner-route-agent.sh
