ARG BASE_BRANCH=devel
ARG FEDORA_VERSION=41
ARG SOURCE=/go/src/github.com/submariner-io/submariner

FROM --platform=${BUILDPLATFORM} quay.io/submariner/shipyard-dapper-base:${BASE_BRANCH} AS builder
ARG FEDORA_VERSION
ARG SOURCE
ARG TARGETPLATFORM

COPY . ${SOURCE}

RUN make -C ${SOURCE} LOCAL_BUILD=1 BUILD_UPX=false bin/${TARGETPLATFORM}/submariner-gateway
RUN make -C ${SOURCE} LOCAL_BUILD=1 BUILD_UPX=false bin/${TARGETPLATFORM}/await-node-ready

FROM --platform=${BUILDPLATFORM} fedora:${FEDORA_VERSION} AS base
ARG FEDORA_VERSION
ARG SOURCE
ARG TARGETPLATFORM

COPY package/dnf_install /

# iproute and iptables are used internally
# libreswan provides IKE
# kmod is required so that libreswan can load modules
RUN /dnf_install -a ${TARGETPLATFORM} -v ${FEDORA_VERSION} -r /output/gateway \
    glibc bash glibc-minimal-langpack coreutils-single \
    libcurl-minimal iproute libreswan kmod

FROM scratch
ARG SOURCE
ARG TARGETPLATFORM

WORKDIR /var/submariner

COPY --from=base /output/gateway /
COPY --from=builder ${SOURCE}/package/submariner.sh ${SOURCE}/package/pluto ${SOURCE}/bin/${TARGETPLATFORM}/submariner-gateway \
  ${SOURCE}/package/await-node-ready.sh ${SOURCE}/bin/${TARGETPLATFORM}/await-node-ready /usr/local/bin/

ENTRYPOINT ["submariner.sh"]
