FROM quay.io/submariner/submariner-iptables-base:devel
ARG TARGETPLATFORM

WORKDIR /var/submariner

RUN dnf -y clean all

COPY package/submariner-route-agent.sh bin/${TARGETPLATFORM}/submariner-route-agent /usr/local/bin/

ENTRYPOINT submariner-route-agent.sh
