FROM registry.access.redhat.com/ubi8/ubi-minimal

WORKDIR /var/submariner

COPY submariner-ipam.sh /usr/local/bin

RUN chmod +x /usr/local/bin/submariner-ipam.sh

COPY submariner-ipam /usr/local/bin

ENTRYPOINT submariner-ipam.sh
