FROM fedora:33 
ARG TARGETPLATFORM

WORKDIR /var/submariner

RUN dnf -y install --nodocs --setopt=install_weak_deps=0 \
           ovn && \
    dnf -y clean all

# install the networkpluginc-sync
COPY package/submariner-networkplugin-syncer.sh bin/${TARGETPLATFORM}/submariner-networkplugin-syncer /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/submariner-networkplugin-syncer.sh"]

USER ${USER_UID}
