FROM fedora:32

RUN dnf -y install --nodocs git-core 'dnf-command(builddep)' rpm-build


WORKDIR /root

RUN git clone https://github.com/libreswan/libreswan --branch main
RUN sed -i -e "s/^%global with_cavstests 1*/%global with_cavstests 0/g" libreswan/packaging/fedora/libreswan.spec 
RUN dnf -y builddep --nodocs libreswan/packaging/fedora/libreswan.spec

RUN make -C libreswan git-rpm 

FROM fedora:32

WORKDIR /var/submariner

# iproute and iptables are used internally
# libreswan or strongswan provide IKE
# procps-ng is needed for sysctl
RUN dnf -y install --nodocs --setopt=install_weak_deps=0 \
           iproute iptables strongswan procps-ng && \
    dnf -y clean all

COPY --from=0 /root/rpmbuild/RPMS/x86_64/* /root/

RUN dnf -y install /root/*.rpm && \
    dnf -y clean all && \
    rm -f /root/*.rpm
COPY package/submariner.sh package/pluto bin/submariner-engine /usr/local/bin/

# Wrapper scripts to use iptables from the host when that's available
COPY package/iptables-wrapper.in /usr/sbin/

#bubu
ENTRYPOINT submariner.sh
