ARG BASE_BRANCH=release-0.21
ARG SOURCE=/go/src/github.com/submariner-io/submariner

FROM --platform=${BUILDPLATFORM} registry.redhat.io/ubi9/go-toolset:latest AS builder
ARG SOURCE
ARG TARGETPLATFORM
ARG BASE_BRANCH

ENV GOEXPERIMENT=strictfipsruntime
ARG BUILD_TAGS="strictfipsruntime"

COPY . ${SOURCE}

USER root
RUN chown -R 1001:0 ${SOURCE}
USER 1001

RUN git config --global --add safe.directory ${SOURCE}

WORKDIR ${SOURCE}

RUN CGO_ENABLED=1 GOARCH=${TARGETPLATFORM##*/} go build \
    -ldflags "-s -w \
    -X github.com/submariner-io/submariner/pkg/versions.version=${BASE_BRANCH} \
    -X github.com/submariner-io/submariner/pkg/versions.gitCommitHash=$(git rev-parse --short HEAD)" \
    -tags "${BUILD_TAGS}" \
    -v -o ${SOURCE}/bin/${TARGETPLATFORM}/submariner-globalnet \
    ${SOURCE}/pkg/globalnet

FROM --platform=${TARGETPLATFORM} registry.redhat.io/ubi9:latest
ARG BASE_BRANCH
ARG SOURCE
ARG SOURCE_DATE_EPOCH
ARG TARGETPLATFORM

RUN dnf -y update && \
    dnf -y install --nodocs iproute iptables-nft nftables ipset shadow-utils grep && \
    dnf clean all

RUN adduser -r -l -u 1001 -G root submariner

WORKDIR /var/submariner

COPY --from=builder \
    ${SOURCE}/bin/${TARGETPLATFORM}/submariner-globalnet \
    ${SOURCE}/package/submariner-globalnet.sh \
    /usr/local/bin/

RUN chown -Rc submariner:root /usr/local/bin
RUN chmod -Rc 775 /usr/local/bin

COPY --from=builder ${SOURCE}/LICENSE /licenses/LICENSE

USER submariner

ENTRYPOINT ["/usr/local/bin/submariner-globalnet.sh"]

LABEL com.redhat.component="submariner-globalnet-container" \
      name="rhacm2/submariner-globalnet-rhel9" \
      version="v0.21.2" \
      summary="Submariner Globalnet" \
      description="The Submariner Globalnet component provides connectivity for overlapping CIDRs in different clusters." \
      io.k8s.display-name="Submariner Globalnet" \
      io.k8s.description="The Submariner Globalnet component provides connectivity for overlapping CIDRs in different clusters." \
      io.openshift.tags="submariner, submariner-globalnet, rhacm" \
      maintainer="multi-cluster-networking@redhat.com" \
      com.github.url="https://github.com/submariner-io/submariner" \
      com.github.commit="${BASE_BRANCH}" \
      cpe="cpe:/a:redhat:acm:2.14::el9" \
      org.opencontainers.image.created="${SOURCE_DATE_EPOCH}"
