ARG ARCH=
FROM ${ARCH}fedora:33

WORKDIR /var/submariner

RUN dnf -y install --nodocs --setopt=install_weak_deps=0 \
           iproute iptables

COPY package/submariner-globalnet.sh bin/submariner-globalnet /usr/local/bin/

# Wrapper scripts to use iptables from the host when that's available
COPY package/iptables-wrapper.in /usr/sbin/

ENTRYPOINT submariner-globalnet.sh
