---
name: Branch Checks

on:
  pull_request:

jobs:
  target_branch:
    name: PR targets branch
    runs-on: ubuntu-latest
    steps:
      - name: Check that the PR targets multi-active-gw
        if: ${{ github.base_ref != 'feature-multi-active-gw' }}
        run: exit 1
