---
name: PR Dependencies

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions:
  pull-requests: write

jobs:
  check:
    name: Check Dependencies
    if: github.repository_owner == 'submariner-io'
    runs-on: ubuntu-latest
    steps:
      - uses: depends-on/depends-on-action@826c144163ac67bf08347590a5f81afd45da63ca  # v0.16.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check-unmerged-pr: true
