---
name: PR Dependencies

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions:
  pull-requests: write

jobs:
  check:
    name: Check Dependencies
    if: github.repository_owner == 'submariner-io'
    runs-on: ubuntu-latest
    steps:
      - uses: depends-on/depends-on-action@e7915c70317af4efc4e6c4a4eb1e9260e215270c  # v0.16.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check-unmerged-pr: true
