---
name: Flake Finder

on:
  schedule:
    - cron: "0 0,1 * * *"

permissions: {}

jobs:
  e2e:
    name: E2E
    if: github.repository_owner == 'submariner-io'
    timeout-minutes: 45
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cable-driver: ['', 'wireguard', 'vxlan']
        extra-toggles: ['', 'ovn']
        globalnet: ['', 'globalnet']
        # Run most tests against the latest K8s version
        k8s_version: ['k8s-latest']
        exclude:
          - cable-driver: wireguard
            extra-toggles: ovn
        include:
          - extra-toggles: dual-stack
          - extra-toggles: dual-stack, globalnet
          - extra-toggles: dual-stack, ovn
          - extra-toggles: ipv6-stack
          # Test top and bottom of supported K8s version range
          - k8s_version: 'k8s-oldest-supported'
    steps:
      - name: Check out the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Run E2E deployment and tests
        uses: submariner-io/shipyard/gh-actions/e2e@devel
        with:
          using: ${{ matrix.cable-driver }} ${{ matrix.extra-toggles }}

      - name: Post mortem
        if: failure()
        uses: submariner-io/shipyard/gh-actions/post-mortem@devel
