---
name: Multi-arch Builds

on:
  pull_request:

permissions: {}

jobs:
  check-multiarch:
    name: Check the multi-arch builds
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - name: Set up QEMU (to support building on non-native architectures)
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3
      - name: Build the multi-arch images
        run: make multiarch-images
      - name: Check that we actually build multi-arch images
        run: bash -c '[ "$(echo package/*.tar)" != "package/*.tar" ]'
