---
name: Multi-arch Builds

on:
  pull_request:

permissions: {}

jobs:
  check-multiarch:
    name: Check the multi-arch builds
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Set up QEMU (to support building on non-native architectures)
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8
      - name: Build the multi-arch images
        run: make multiarch-images
      - name: Check that we actually build multi-arch images
        run: bash -c '[ "$(echo package/*.tar)" != "package/*.tar" ]'
