---
name: Release Images

on:
  workflow_dispatch:
  push:
    branches:
      - release-0.24
      - release-*

permissions: {}

jobs:
  release:
    name: Release Images
    if: github.repository_owner == 'submariner-io'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          fetch-depth: 0

      - name: Build and release new images
        uses: submariner-io/shipyard/gh-actions/release-images@release-0.24
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
